package http

import (
	"context"
	"encoding/json"
	"net/http"

	"github.com/sundaycrafts/depgraph/gen"
	"github.com/sundaycrafts/depgraph/internal/domain"
	"github.com/sundaycrafts/depgraph/internal/ports"
)

// Adapter implements ports.ServerPort.
// It registers routes generated by oapi-codegen and handles request/response
// validation through the generated ServerInterfaceWrapper.
type Adapter struct {
	graph  domain.Graph
	editor ports.EditorPort
}

var _ ports.ServerPort = (*Adapter)(nil)
var _ gen.ServerInterface = (*Adapter)(nil)

func New(editor ports.EditorPort) *Adapter {
	return &Adapter{editor: editor}
}

func (a *Adapter) Serve(ctx context.Context, graph domain.Graph) error {
	a.graph = graph

	mux := http.NewServeMux()
	apiHandler := gen.Handler(a)

	// Mount API routes and static SPA files.
	mux.Handle("/graph", apiHandler)
	mux.Handle("/file", apiHandler)
	mux.Handle("/", http.FileServer(http.FS(StaticFiles)))

	srv := &http.Server{Addr: ":8080", Handler: mux}

	go func() {
		<-ctx.Done()
		srv.Shutdown(context.Background()) //nolint:errcheck
	}()

	if err := srv.ListenAndServe(); err != http.ErrServerClosed {
		return err
	}
	return nil
}

func (a *Adapter) GetGraph(w http.ResponseWriter, _ *http.Request) {
	panic("not implemented")
}

func (a *Adapter) GetFile(w http.ResponseWriter, _ *http.Request, params gen.GetFileParams) {
	panic("not implemented")
}

func writeJSON(w http.ResponseWriter, status int, v any) {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(status)
	json.NewEncoder(w).Encode(v) //nolint:errcheck
}
